### ISSUE TITLE
Beta 1 version npm install issues

### ISSUE THREAD

**Issue by mjftw** [whereby/browser-sdk#106]
I'm seeing some issues when trying to install your new Beta1 version with npm:

```
$ npm i @whereby.com/browser-sdk@2.0.0-beta1
npm ERR! code 1
npm ERR! The git reference could not be found
npm ERR! command git --no-replace-objects checkout v5.3.0
npm ERR! error: pathspec 'v5.3.0' did not match any file(s) known to git

npm ERR! A complete log of this run can be found in: /home/merlin/.npm/_logs/2023-10-30T07_16_16_902Z-debug-0.log
```

I thought it might be my environment causing issues so tried the previous Apla26 version, but this works without issue.

```
$ npm i @whereby.com/browser-sdk@2.0.0-alpha26
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3

added 75 packages, changed 1 package, and audited 466 packages in 14s

130 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (1 moderate, 6 high, 1 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

Environment info:

```
$ node --version
v20.8.1

$ npm --version
10.1.0
```

Very interested to try out the shiny new browser SDK now it's officially entered beta!

**Comment by havardholvik** [comment]
Can confirm I am able to reproduce using the same versions of node and npm as you @mjftw. Strange enough, adding the same package with yarn works.

Looking at the error, version v5.3.0 seems to be a new dependency we have introduced lately (a fork of a previous dependency). Must be something related to this change, will investigate further.

**Comment by havardholvik** [comment]
Seems like there was an mismatch with our dependency git tag, where yarn was smart enough to match and npm was not (could be discussed how smart it is to fuzzy match git tags though 😄 ). However, we have now added the correct tag to our Github repo, and npm install works for me now locally. Can you try again on your side @mjftw ?

**Comment by mjftw** [comment]
Thanks a bunch, that's fixed things for me and Beta-1 is installed successfully 👍🏽

**Comment by mjftw** [comment]
Closing as all working now, thanks!

**Comment by mjftw** [comment]
Just noticed that I lose the typings moving from Beta26 to Alpha1 by the way.

On Alpha 1:
```
Could not find a declaration file for module '@whereby.com/browser-sdk'. '/home/merlin/learning/transcript-sandbox/nextjs-app/node_modules/@whereby.com/browser-sdk/dist/lib.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/whereby.com__browser-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module '@whereby.com/browser-sdk';`ts(7016)
module "/home/merlin/learning/transcript-sandbox/nextjs-app/node_modules/@whereby.com/browser-sdk/dist/lib.cjs"
```

On Beta 26 the type imports are working fine.
