### ISSUE TITLE
The new beta SDK does not export anything usable

### ISSUE THREAD

**Issue by NokLam-hhl** [whereby/browser-sdk#116]
# Issues

When I try the [beta version](https://www.npmjs.com/package/@whereby.com/browser-sdk/v/2.0.0-beta1) and use it according to the README, found out that the package does not export anything usable and the TS definitions are missing as well.

Rendered screen on NextJS dev mode using `next dev`:

<img width="761" alt="Screenshot 2023-11-03 at 14 14 14" src="https://github.com/whereby/browser-sdk/assets/109536948/dcc4ec38-7b0f-4292-b457-4da8eb4d5b14">

TS errors in VS Code:

<img width="626" alt="Screenshot 2023-11-03 at 14 12 07" src="https://github.com/whereby/browser-sdk/assets/109536948/566f7bb2-9cbd-49f2-8209-cf5b3b1c2d55">
<img width="1018" alt="Screenshot 2023-11-03 at 14 11 48" src="https://github.com/whereby/browser-sdk/assets/109536948/1740c5cf-edb4-413e-bf46-14e6049d782f">

These errors do not exist for the last [alpha version.](https://www.npmjs.com/package/@whereby.com/browser-sdk/v/2.0.0-alpha26).

# How to reproduce

Clone and run this repo: https://github.com/NokLam-hhl/whereby-sdk-fail-demo

**Comment by thyal** [comment]
Hi! We've updated the import paths - you can see the README here: https://github.com/whereby/browser-sdk/tree/development

The updated README is not deployed to NPM yet, sorry about that.

Updating your import statements to `... from @whereby.com/browser-sdk/react` (for the react hooks) and `... from @whereby.com/browser-sdk/embed` (for the embed element) should fix the issue. 

Can you try that and see if it works?

**Comment by NokLam-hhl** [comment]
> Hi! We've updated the import paths - you can see the README here: https://github.com/whereby/browser-sdk/tree/development
> 
> The updated README is not deployed to NPM yet, sorry about that.
> 
> Updating your import statements to `... from "@whereby.com/browser-sdk/react"` (for the react hooks) and `... from "@whereby.com/browser-sdk/embed"` (for the embed element) should fix the issue.
> 
> Can you try that and see if it works?

@thyal Nice, it looks like it is working perfectly after following your instruction. When a PR of updating that README is raised could you link that to this issue please?

**Comment by thyal** [comment]
Glad to hear that it works. Yes, I'll make sure that it's linked to this issue 👍
