### ISSUE TITLE
TypeError in WherebyEmbed Custom Element due to Uninitialized this.roomUrl

### ISSUE THREAD

**Issue by doguabaris** [whereby/browser-sdk#172]
In the WherebyEmbed custom element, a TypeError is encountered when attempting to access the origin property of roomUrl within the onmessage event handler. This issue arises if the onmessage handler is called before this.roomUrl is set or if roomUrl is not correctly initialized due to parsing errors in the room attribute.

To address this, a guard can be added to ensure this.roomUrl is defined before accessing its properties. Modify the code at line 104 as follows:

Replace:
`if (origin !== this.roomUrl.origin) return; `

With:
`if (!this.roomUrl || origin !== this.roomUrl.origin) return;`

https://github.com/whereby/browser-sdk/blob/580f6096ccf9c6867d2eb62073cd8be84102f983/src/lib/index.js#L104

**Comment by havardholvik** [comment]
Hi there 👋  Nice catch. We'll get this fix into our next release 👍
