### ISSUE TITLE
Listening Recording Events

### ISSUE THREAD

**Issue by tarikcaliskan** [whereby/browser-sdk#45]
Thank you for developing the browser SDK for Whereby. 

The recording feature, which is supported by the Whereby embeds, is quite useful. However, I have a question regarding listening to recording events while in the room. Is there a way to do this? Do you have any plans to develop such a feature in the future?

Thanks in advance!

**Comment by nrolls** [comment]
Hi @tarikcaliskan ! Thanks for the kind words and taking some time to submit your question. That's a great thought! I'm not sure if this is actively being developed, however it's something that might be within scope of one of our engineers upcoming projects.

Out of curiosity, would you mind sharing a little bit how you'd ideally like to use this feature? It can be helpful for us to have some context into it's usage.

Thank you!

**Comment by tarikcaliskan** [comment]
The primary purpose of this feature is to detect user actions related to recording and provide a listener for those actions. According to the documentation, Whereby already has [some support](https://docs.whereby.com/embedding-rooms/in-a-web-page/using-the-whereby-embed-element#listening-to-events) for listening to certain events. With these listeners, applications can make action (API) calls or update the application state.

On Whereby Embed SDK, it would be nice if we can create event listeners for these actions

**Example:**
```
elm.addEventListener("recording_start", logEvent)
elm.addEventListener("recording_end", logEvent)
```

----------

Another option is to use Whereby webhooks to trigger events. When a `recording_start` or `recording_end` event occurs, a call to the webhook should be made.

**Comment by tarikcaliskan** [comment]
Looks like it's implemented as mentioned in the [docs](https://docs.whereby.com/embedding-rooms/in-a-web-page/using-the-whereby-embed-element#listening-to-events).


Thanks a lot! 🚀
