### ISSUE TITLE
Picture-in-picture toggle event

### ISSUE THREAD

**Issue by sivajiDsmart** [whereby/browser-sdk#70]
Hi everyone, 

Is there any event for a Picture-in-picture toggle?
I want the main video <whereby-embed> element to hide while triggering Picture-in-picture to access my web page below.
Thanks in advance.

**Comment by kevinwhereby** [comment]
Hi @sivajiDsmart, we've added a PiP toggle event, you can listen for it like so:

```typescript
  const elm = document.querySelector("whereby-embed");

**Comment by sivajiDsmart** [comment]
This works perfectly.
Thank you so much @kevinwhereby
