### ISSUE TITLE
Typescript typings module 

### ISSUE THREAD

**Issue by mjftw** [whereby/browser-sdk#99]
I'm trying out the new Browser SDK alpha, but seeing some import errors.
Am I right in thinking there are no Typescript type definitions for the module? 

This is a key feature we'd need to adopt Whereby at my company, so keen to hear more on this.
We would otherwise attempt to add the type module definition ourself, but this is likely to be error prone since we are not the authors.

From what I remember, there are also no type definitions in the main released Embedded SDK version `v1.11` right?

```typescript
import { useLocalMedia, VideoView } from "@whereby.com/browser-sdk";
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
Could not find a declaration file for module '@whereby.com/browser-sdk'. '/home/merlin/repos/mycoolapp/node_modules/@whereby.com/browser-sdk/dist/lib.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/whereby.com__browser-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module '@whereby.com/browser-sdk';`ts(7016)
```

Version info:
```
$ npm --version
8.5.5

$ node --version
v16.15.0
 ~/r/hello_app (
```

`package.json` `"dependencies"` snippet:
```
    "@whereby.com/browser-sdk": "^1.11.0",
    "typescript": "^5.1.6",
```

**Comment by havardholvik** [comment]
Looking at your dependencies in package.json, it seems you are using our ^1.11.0 version. This version does not have TypeScript support, nor the React hooks you are trying to use.

Could you try adding `2.0.0-alpha26` as your version and see if you get the types?

**Comment by mjftw** [comment]
Hi Havard, thanks for getting back to me.
I'm now on the `2.0.0-alpha26version and doesn't look like I have types.
Installed with `npm i @whereby.com/browser-sdk@2.0.0-alpha26`

![image](https://github.com/whereby/browser-sdk/assets/8429712/61cda431-7427-49f7-9943-5a8024275900)

**Comment by mjftw** [comment]
Closing as issue superseded by https://github.com/whereby/browser-sdk/issues/107
Looks like the typings issue is part of a bigger issue I'm facing with using the react components at all.

**Comment by mjftw** [comment]
Closing as issue superseded by https://github.com/whereby/browser-sdk/issues/107
Looks like the typings issue is part of a bigger issue I'm facing with using the react components at all.
